modLoader="javafml"
logoFile="logo.png"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="卓清婉, 凌墨问, 可怜Bot, 五世桃花亭"
authors="${mod_authors}"
displayURL="https://rts.ciallo.ltd/"
description='''
Build, manage storage, and interact with your base from an overhead RTS-style building panel.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

